a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('Só tem números? ', a.isalnum())
print('Só tem letras? ', a.isalpha())
print('Só tem espaços? ', a.isalnum())
print('Está em maiusculo ? ', a.isupper())
print('Está em minusculo? ', a.islower())
